# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10

  - name: Publications
    weight: 20
    identifier: "publications"
  - name: All
    url: 'publication'
    weight: 21
    parent: "publications"
  - name: Articles
    url: 'articles'
    weight: 22
    parent: "publications"
  - name: Preprints
    url: 'preprint'
    weight: 23
    parent: "publications"

  - name: "Questionnaires"
    identifier: "questionnaires"
    weight: 30
  - name: "If-Then Planning Scale (ITPS)"
    parent: "questionnaires"
    url: "#test"
    weight: 30

  - name: "Quests"
    url: "/questionnaires/"
    weight: 40
  # - name: Q
  #   parent: "questionnaires"
  #   url: 'itps'
  #   weight: 20

  # - name: Talks
  #   url: '#talks'
  #   weight: 40
  # - name: Education
  #   url: 'education'
  #   weight: 40
  - name: Contact
    url: '#contact'
    weight: 50

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
